### ISSUE TITLE
切换Xray v.1.8.12版本报错

### ISSUE THREAD

**Issue by coulsontl** [yonggekkk/x-ui-yg#38]
```
Xray 1.8.12 (Xray, Penetrates Everything.) 416f2df (go1.22.3 linux/arm64)

A unified platform for anti-censorship.

2024/05/22 18:58:57 [Info] infra/conf/serial: Reading config: bin/config.json

2024/05/22 18:58:57 [Debug] infra/conf: kernel mode is enabled as it's supported and permission is sufficient

2024/05/22 18:58:57 [Warning] core: Xray 1.8.12 started

panic: runtime error: index out of range [-1]

goroutine 98 [running]:

github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0x4000124b80, {0x108dea0, 0x1a52f00}, {{0x108e450, 0x40006f28c8}, 0x1051, 0x3})

github.com/xtls/xray-core/app/proxyman/outbound/handler.go:288 +0xac8

github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).connectTo(0x400003d400, 0x40001e9b30)

github.com/xtls/xray-core/proxy/wireguard/bind.go:131 +0x54

github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).Send(0x400003d400, {0x4000dfc060, 0x1, 0xff051cd3e108?}, {0x1092e98?, 0x40001e9b30})

github.com/xtls/xray-core/proxy/wireguard/bind.go:174 +0x54

golang.zx2c4.com/wireguard/device.(*Peer).SendBuffers(0x40004f9508, {0x4000dfc060, 0x1, 0x1})

golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/peer.go:136 +0x218

golang.zx2c4.com/wireguard/device.(*Peer).SendHandshakeInitiation(0x40004f9508, 0x8?)

golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:136 +0x43c

golang.zx2c4.com/wireguard/device.(*Peer).SendStagedPackets(0x40004f9508)

golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:350 +0xd4

golang.zx2c4.com/wireguard/device.(*Device).RoutineReadFromTUN(0x400029c788)

golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:293 +0x694

created by golang.zx2c4.com/wireguard/device.NewDevice in goroutine 71

golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:322 +0x3e8
```

**Comment by yonggekkk** [comment]
更新到最新版了吗

**Comment by coulsontl** [comment]
> 更新到最新版了吗

xui已更新到最新版本

**Comment by yonggekkk** [comment]
面版有没有error报错显示

**Comment by coulsontl** [comment]
> 面版有没有error报错显示

有error报错，点问号就是我最上面发的错误信息
<img width="515" alt="image" src="https://github.com/yonggekkk/x-ui-yg/assets/149155411/0c535128-b039-4b87-ade9-671f1f0b2cf2">

**Comment by yonggekkk** [comment]
点黑色的问号，截图

**Comment by coulsontl** [comment]
> 点黑色的问号，截图

<img width="276" alt="image" src="https://github.com/yonggekkk/x-ui-yg/assets/149155411/8d347784-502d-4abb-88f5-8a7244f1af8e">

**Comment by yonggekkk** [comment]
卸载重装下试试

**Comment by coulsontl** [comment]
> 卸载重装下试试

试了卸载重装还是报同样的错误

**Comment by yonggekkk** [comment]
什么vps？换个系统试试

**Comment by coulsontl** [comment]
> 什么vps？换个系统试试

甲骨文的ARM64，Ubuntu 22.04.4 LTS，不能换系统……

**Comment by yonggekkk** [comment]
> > 什么vps？换个系统试试
> 
> 甲骨文的ARM64，Ubuntu 22.04.4 LTS，不能换系统……

Dd过吗？

**Comment by coulsontl** [comment]
> 更新到最新版了吗

xui已更新到最新版本

> > > 什么vps？换个系统试试
> > 
> > 
> > 甲骨文的ARM64，Ubuntu 22.04.4 LTS，不能换系统……
> 
> Dd过吗？

没有DD过

**Comment by coulsontl** [comment]
升级最新的v1.8.13就好了，是Xray的bug....

**Comment by yonggekkk** [comment]
OK
